### ISSUE TITLE
Nodes do not produce blocks, potentially due to encryption issues

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/integration#2]
Currently nodes connect but do not produce blocks. This is very likely caused by nodes not using keys correctly (The behavior is very similar to what happened here https://github.com/nearprotocol/nearcore/issues/662 ).

#1 is relevant, but shouldn't have prevented nodes from producing blocks, because three nodes out of four would still be able to create consensus.

**Comment by azban** [comment]
this was fixed by putting keystore inside of storage directory
